In [43]:
import pandas as pd
import numpy as np

print("Setup Successful")

Setup Successful

In [44]:
from google.colab import files

uploaded = files.upload()

Saving Atlantic_South_Korea.csv to Atlantic_South_Korea (1).csv

In [45]:
import pandas as pd

file_name = list(uploaded.keys())[0]

print("Uploaded file:", file_name)

Uploaded file: Atlantic_South_Korea (1).csv

In [46]:
import pandas as pd

df = pd.read_csv("Atlantic_South_Korea.csv", encoding='latin1')

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [47]:
df.head()

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url
0,18-05-2024,1,Like Crazy,Jimin,93,212241,single,6,False,https://i.scdn.co/image/ab67616d0000b2732b4607...
1,18-05-2024,2,UNFORGIVEN (feat. Nile Rodgers),LE SSERAFIM,87,182148,album,13,False,https://i.scdn.co/image/ab67616d0000b273d71fd7...
2,18-05-2024,3,Spicy,aespa,81,197040,single,6,False,https://i.scdn.co/image/ab67616d0000b27304878a...
3,18-05-2024,4,I AM,IVE,89,183853,album,11,False,https://i.scdn.co/image/ab67616d0000b27325ef3c...
4,18-05-2024,5,Queencard,(G)I-DLE,71,161240,single,6,False,https://i.scdn.co/image/ab67616d0000b27382dd24...

In [48]:
df.shape

(27800, 10)

In [49]:
df.columns

Index(['date', 'position', 'song', 'artist', 'popularity', 'duration_ms',
       'album_type', 'total_tracks', 'is_explicit', 'album_cover_url'],
      dtype='object')

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27800 entries, 0 to 27799
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             27800 non-null  object
 1   position         27800 non-null  int64
 2   song             27800 non-null  object
 3   artist           27800 non-null  object
 4   popularity       27800 non-null  int64
 5   duration_ms      27800 non-null  int64
 6   album_type       27800 non-null  object
 7   total_tracks     27800 non-null  int64
 8   is_explicit      27800 non-null  bool
 9   album_cover_url  27800 non-null  object
dtypes: bool(1), int64(4), object(5)
memory usage: 1.9+ MB

In [51]:
df.isnull().sum()

date               0
position           0
song               0
artist             0
popularity         0
duration_ms        0
album_type         0
total_tracks       0
is_explicit        0
album_cover_url    0
dtype: int64

In [52]:
df.duplicated().sum()

np.int64(16)

In [53]:
df.describe()

           position    popularity    duration_ms  total_tracks
count  27800.000000  27800.000000   27800.000000  27800.000000
mean      25.500000     76.927446  191780.020468      5.894640
std       14.431129     12.907857   35611.039130      4.674461
min        1.000000      0.000000   36226.000000      1.000000
25%       13.000000     67.000000  170386.000000      2.000000
50%       25.500000     79.000000  188498.000000      6.000000
75%       38.000000     86.000000  212253.000000     10.000000
max       50.000000    100.000000  547733.000000     40.000000

In [54]:
# Create a copy of the dataset
df_clean = df.copy()

# Convert date column to datetime format
df_clean['date'] = pd.to_datetime(df_clean['date'])

# Remove duplicate rows
df_clean = df_clean.drop_duplicates()

print("Rows after cleaning:", len(df_clean))

Rows after cleaning: 27784

/tmp/ipykernel_3404/3501305674.py:5: UserWarning:

Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.

In [55]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27784 entries, 0 to 27799
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             27784 non-null  datetime64[ns]
 1   position         27784 non-null  int64
 2   song             27784 non-null  object
 3   artist           27784 non-null  object
 4   popularity       27784 non-null  int64
 5   duration_ms      27784 non-null  int64
 6   album_type       27784 non-null  object
 7   total_tracks     27784 non-null  int64
 8   is_explicit      27784 non-null  bool
 9   album_cover_url  27784 non-null  object
dtypes: bool(1), datetime64[ns](1), int64(4), object(4)
memory usage: 2.1+ MB

In [56]:
print("Unique Songs :", df_clean['song'].nunique())

print("Unique Artists :", df_clean['artist'].nunique())

print("Album Types :", df_clean['album_type'].unique())

print("Date Range Start :", df_clean['date'].min())

print("Date Range End :", df_clean['date'].max())

Unique Songs : 526
Unique Artists : 194
Album Types : ['single' 'album' 'compilation']
Date Range Start : 2024-05-18 00:00:00
Date Range End : 2025-11-27 00:00:00

In [57]:
df_clean[['song','artist']].drop_duplicates().head(20)

,song,artist
0,Like Crazy,Jimin
1,UNFORGIVEN (feat. Nile Rodgers),LE SSERAFIM
2,Spicy,aespa
3,I AM,IVE
4,Queencard,(G)I-DLE
5,Like Crazy (English Version),Jimin
6,Set Me Free Pt.2,Jimin
7,????,YOASOBI
8,Kitsch,IVE
9,Cupid - Twin Ver.,FIFTY FIFTY
10,OMG,NewJeans
11,NIGHT DANCER,imase
12,Super,SEVENTEEN
13,"Angel Pt. 1 (feat. Jimin of BTS, JVKE & Muni L...",Fast & Furious: The Fast Saga & Jimin & BTS
14,Ditto,NewJeans
15,Cupid,FIFTY FIFTY
16,Allergy,(G)I-DLE
17,Hype Boy,NewJeans
18,The Planet,BTS
19,FLOWER,JISOO

In [58]:
df_clean['album_type'].value_counts()

album_type
single         17938
album           9845
compilation        1
Name: count, dtype: int64

In [59]:
song_presence = (
    df_clean.groupby(['song', 'artist'])
    .size()
    .reset_index(name='days_on_chart')
)

song_presence.head()

                           song                         artist  days_on_chart
0               1-800-hot-n-fun                    LE SSERAFIM              8
1                  24YB (Intro)                    YANGHONGWON              3
2           3D (Alternate Ver.)        Jung Kook & Jack Harlow             20
3  3D (Justin Timberlake Remix)  Jung Kook & Justin Timberlake              6
4        3D (feat. Jack Harlow)                      Jung Kook            308

In [60]:
song_presence.sort_values(
    by='days_on_chart',
    ascending=False
).head(20)

                                    song           artist  days_on_chart
254                           Like Crazy            Jimin            554
263                           London Boy  Lim Young Woong            521
176                        Grain of Sand  Lim Young Woong            516
342                             Polaroid  Lim Young Woong            509
213                If We Ever Meet Again  Lim Young Woong            504
271                        Love Me Again                V            469
382                     Set Me Free Pt.2            Jimin            429
256         Like Crazy (English Version)            Jimin            429
444                            Super Shy         NewJeans            409
33                                 Alone            Jimin            407
151                             Face-off            Jimin            406
352                              Rainbow  Lim Young Woong            405
120                            Do or Die  Lim Young Woong            390
387  Seven (feat. Latto) (Explicit Ver.)        Jung Kook            385
426                 Standing Next to You        Jung Kook            384
118                                Ditto         NewJeans            374
218                     Interlude : Dive            Jimin            365
327                  Our Blues, Our Life  Lim Young Woong            362
131                                  ETA         NewJeans            340
88                      Closer Than This            Jimin            335

In [61]:
print("Average Days on Chart:",
      round(song_presence['days_on_chart'].mean(),2))

Average Days on Chart: 51.36

In [62]:
df_sorted = df_clean.sort_values(['song', 'date'])

df_sorted['prev_song'] = df_sorted['song'].shift(1)

df_sorted['is_new_streak'] = (
    df_sorted['song'] != df_sorted['prev_song']
)

reentry = df_sorted.groupby(['song', 'artist'])['is_new_streak'].sum().reset_index()

reentry = reentry.rename(columns={'is_new_streak': 'reentry_count'})

reentry.sort_values('reentry_count', ascending=False).head(20)

,song,artist,reentry_count
540,"yes, and?",Ariana Grande,1
0,1-800-hot-n-fun,LE SSERAFIM,1
1,24YB (Intro),YANGHONGWON,1
2,3D (Alternate Ver.),Jung Kook & Jack Harlow,1
3,3D (Justin Timberlake Remix),Jung Kook & Justin Timberlake,1
539,wherever u r (ft. V of BTS),UMI & V,1
5,3D (feat. Jack Harlow),Jung Kook & Jack Harlow,1
6,3D (feat. Jack Harlow) (Alternate Ver.),Jung Kook & Jack Harlow,1
7,3D (feat. Jack Harlow) (Instrumental),Jung Kook & Jack Harlow,1
8,3D (feat. Jack Harlow) (MK Remix),Jung Kook & Jack Harlow & MK,1
9,990 (Feat. Kim Ximya),Beenzino,1
10,? ???? ? ? ??,DAY6,1
523,don't wanna break up again,Ariana Grande,1
522,bye,Ariana Grande,1
521,Young Man,HYUKOH & ???? Sunset Rollercoaster,1
520,You Were Beautiful,DAY6,1
519,You & Me (Coachella ver.),JENNIE,1
518,You & Me,JENNIE,1
517,"Yes or No (Feat. HUH YUNJIN of LE SSERAFIM, Cr...",GroovyRoom,1
516,"Yes or No (Feat. ??? of LE SSERAFIM, Crush)",GroovyRoom & HUH YUNJIN,1

In [63]:
reentry.describe()

       reentry_count
count     541.000000
mean        0.972274
std         0.164340
min         0.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         1.000000

In [64]:
df_re = df_clean.copy()

# Sort properly for time analysis
df_re = df_re.sort_values(['song', 'date'])

# Check if song was present previous day
df_re['prev_presence'] = df_re.groupby('song')['position'].shift(1)

# If previous is NaN → first entry
df_re['is_first_entry'] = df_re['prev_presence'].isna()

# Re-entry happens when song appears again after missing days
df_re['is_reentry'] = (
    (df_re['is_first_entry'] == False) &
    (df_re['prev_presence'].isna())
)

# Correct method: detect gaps in presence
df_re['was_present_before'] = df_re.groupby('song')['date'].diff().dt.days > 1

df_re['reentry_flag'] = (
    df_re['was_present_before'].fillna(False)
)

reentry_final = df_re.groupby(['song','artist'])['reentry_flag'].sum().reset_index()

reentry_final.rename(columns={'reentry_flag':'reentry_count'}, inplace=True)

reentry_final.sort_values('reentry_count', ascending=False).head(20)

                                  song           artist  reentry_count
327                Our Blues, Our Life  Lim Young Woong             31
118                              Ditto         NewJeans             27
21                           A bientot  Lim Young Woong             24
315                          New Jeans         NewJeans             23
200                           Hype Boy         NewJeans             21
218                   Interlude : Dive            Jimin             21
352                            Rainbow  Lim Young Woong             19
131                                ETA         NewJeans             18
419                           Somebody        Jung Kook             16
98                        Cruel Summer     Taylor Swift             16
322                                OMG         NewJeans             15
82                      Christmas Love            Jimin             14
268               Love Always Run Away  Lim Young Woong             14
89   Closer to You (feat. Major Lazer)        Jung Kook             13
336                      Perfect Night      LE SSERAFIM             13
520                 You Were Beautiful             DAY6             13
506                  Who (Funky Remix)            Jimin             12
505         Who (Beautiful Mind Remix)            Jimin             12
205                         I Love You  Lim Young Woong             12
42                           Attention         NewJeans             10

In [65]:
momentum_df = df_clean.copy()

# Merge re-entry data
momentum_df = momentum_df.merge(
    reentry_final,
    on=['song','artist'],
    how='left'
)

momentum_df['reentry_count'] = momentum_df['reentry_count'].fillna(0)

# Create song-level metrics
song_metrics = momentum_df.groupby(['song','artist']).agg(
    avg_popularity=('popularity','mean'),
    total_days=('date','count'),
    reentry_count=('reentry_count','max')
).reset_index()

# Normalize simple scores
song_metrics['momentum_score'] = (
    song_metrics['avg_popularity'] * 0.5 +
    song_metrics['total_days'] * 0.3 +
    song_metrics['reentry_count'] * 10
)

song_metrics.sort_values('momentum_score', ascending=False).head(20)

,song,artist,avg_popularity,total_days,reentry_count,momentum_score
327,"Our Blues, Our Life",Lim Young Woong,59.044199,362,31,448.122099
118,Ditto,NewJeans,84.058824,374,27,424.229412
218,Interlude : Dive,Jimin,77.106849,365,21,358.053425
315,New Jeans,NewJeans,81.679715,281,23,355.139858
21,A bientot,Lim Young Woong,58.773050,282,24,353.986525
200,Hype Boy,NewJeans,82.570093,321,21,347.585047
352,Rainbow,Lim Young Woong,58.920988,405,19,340.960494
131,ETA,NewJeans,83.402941,340,18,323.701471
263,London Boy,Lim Young Woong,64.205374,521,10,288.402687
322,OMG,NewJeans,86.283912,317,15,288.241956
98,Cruel Summer,Taylor Swift,97.410359,251,16,284.005179
213,If We Ever Meet Again,Lim Young Woong,60.142857,504,8,261.271429
151,Face-off,Jimin,78.763547,406,10,261.181773
254,Like Crazy,Jimin,89.216606,554,5,260.808303
176,Grain of Sand,Lim Young Woong,65.155039,516,7,257.377519
336,Perfect Night,LE SSERAFIM,85.611511,278,13,256.205755
444,Super Shy,NewJeans,87.418093,409,6,226.409046
271,Love Me Again,V,88.528785,469,4,224.964392
342,Polaroid,Lim Young Woong,62.117878,509,4,223.758939
33,Alone,Jimin,77.985258,407,6,221.092629

In [66]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

song_metrics_scaled = song_metrics.copy()

song_metrics_scaled[['avg_popularity','total_days','reentry_count']] = scaler.fit_transform(
    song_metrics_scaled[['avg_popularity','total_days','reentry_count']]
)

song_metrics_scaled['momentum_score_final'] = (
    song_metrics_scaled['avg_popularity'] * 0.5 +
    song_metrics_scaled['total_days'] * 0.3 +
    song_metrics_scaled['reentry_count'] * 0.2
)

song_metrics_scaled.sort_values('momentum_score_final', ascending=False).head(20)

,song,artist,avg_popularity,total_days,reentry_count,momentum_score,momentum_score_final
118,Ditto,NewJeans,0.842695,0.674503,0.870968,424.229412,0.797892
254,Like Crazy,Jimin,0.894402,1.000000,0.161290,260.808303,0.779459
98,Cruel Summer,Taylor Swift,0.976545,0.452080,0.516129,284.005179,0.727122
271,Love Me Again,V,0.887507,0.846293,0.129032,224.964392,0.723448
200,Hype Boy,NewJeans,0.827770,0.578662,0.677419,347.585047,0.722968
218,Interlude : Dive,Jimin,0.773001,0.658228,0.677419,358.053425,0.719453
131,ETA,NewJeans,0.836120,0.613020,0.580645,323.701471,0.718095
315,New Jeans,NewJeans,0.818844,0.506329,0.741935,355.139858,0.709708
322,OMG,NewJeans,0.865002,0.571429,0.483871,288.241956,0.700704
426,Standing Next to You,Jung Kook,0.918233,0.692586,0.161290,210.996875,0.699150
444,Super Shy,NewJeans,0.876372,0.737794,0.193548,226.409046,0.698234
327,"Our Blues, Our Life",Lim Young Woong,0.591922,0.652803,1.000000,448.122099,0.691802
151,Face-off,Jimin,0.789609,0.732369,0.322581,261.181773,0.679032
263,London Boy,Lim Young Woong,0.643663,0.940325,0.322581,288.402687,0.668445
387,Seven (feat. Latto) (Explicit Ver.),Jung Kook,0.864551,0.694394,0.129032,198.619481,0.666400
256,Like Crazy (English Version),Jimin,0.823995,0.773960,0.096774,199.796737,0.663540
336,Perfect Night,LE SSERAFIM,0.858261,0.500904,0.419355,256.205755,0.663273
382,Set Me Free Pt.2,Jimin,0.813035,0.773960,0.096774,199.250117,0.658060
176,Grain of Sand,Lim Young Woong,0.653183,0.931284,0.225806,257.377519,0.651138
33,Alone,Jimin,0.781807,0.734177,0.193548,221.092629,0.649866

In [67]:
import plotly.io as pio
pio.renderers.default = "colab"

In [68]:
!pip install plotly

Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (26.2)

In [69]:
import plotly.express as px

top_songs = song_metrics_scaled.sort_values(
    'momentum_score_final',
    ascending=False
).head(15)

fig = px.bar(
    top_songs,
    x='momentum_score_final',
    y='song',
    color='artist',
    orientation='h',
    title='Top 15 Songs by Momentum Score'
)

fig.show()

In [70]:
fig = px.histogram(
    reentry_final,
    x='reentry_count',
    nbins=20,
    title='Distribution of Song Re-entry Frequency'
)

fig.show()

In [71]:
song_album_type = df_clean[['song', 'artist', 'album_type']].drop_duplicates()
song_metrics_scaled = song_metrics_scaled.merge(
    song_album_type,
    on=['song', 'artist'],
    how='left'
)

album_type_score = (
    song_metrics_scaled
    .groupby('album_type')['momentum_score_final']
    .mean()
    .reset_index()
)

album_type_score

    album_type  momentum_score_final
0        album              0.362513
1  compilation              0.135338
2       single              0.395194

In [72]:
fig = px.bar(
    album_type_score,
    x='album_type',
    y='momentum_score_final',
    title='Average Momentum Score by Album Type',
    text='momentum_score_final'
)

fig.show()

In [73]:
song_explicit_info = df_clean[['song', 'artist', 'is_explicit']].drop_duplicates()
song_metrics_scaled = song_metrics_scaled.merge(
    song_explicit_info,
    on=['song', 'artist'],
    how='left'
)

explicit_score = (
    song_metrics_scaled
    .groupby('is_explicit')['momentum_score_final']
    .mean()
    .reset_index()
)

explicit_score

   is_explicit  momentum_score_final
0        False              0.387661
1         True              0.349871

In [74]:
fig = px.bar(
    explicit_score,
    x='is_explicit',
    y='momentum_score_final',
    title='Momentum Score by Explicit Content',
    text='momentum_score_final'
)

fig.show()

In [75]:
fandom_score = (
    song_metrics_scaled
    .groupby('artist')
    .agg(
        avg_momentum=('momentum_score_final', 'mean'),
        total_re_entries=('reentry_count', 'sum')
    )
    .reset_index()
)

fandom_score.head()

       artist  avg_momentum  total_re_entries
0     $ecrecy      0.190476          0.000000
1    (G)I-DLE      0.416494          0.290323
2        10CM      0.403269          0.096774
3        AKMU      0.372229          0.161290
4  ASH ISLAND      0.246699          0.000000

In [76]:
top_fandom = fandom_score.sort_values(
    by='total_re_entries',
    ascending=False
).head(15)

fig = px.bar(
    top_fandom,
    x='total_re_entries',
    y='artist',
    orientation='h',
    title='Top Artists by Re-entry Frequency'
)

fig.show()

In [77]:
#Histogram of Momentum Scores
import plotly.express as px

fig = px.histogram(
    song_metrics_scaled,
    x='momentum_score_final',
    nbins=30,
    title='Distribution of Momentum Scores',
    labels={'momentum_score_final': 'Momentum Score'},
    marginal='box'
)

fig.show()

In [78]:
#Histogram of Momentum Scores
#Basic Statistics
song_metrics_scaled['momentum_score_final'].describe()

count    567.000000
mean       0.380730
std        0.131929
min        0.000000
25%        0.305231
50%        0.390977
75%        0.455579
max        0.797892
Name: momentum_score_final, dtype: float64

In [79]:
#Categorize Momentum Levels
def momentum_level(score):
    if score >= 0.75:
        return "High"
    elif score >= 0.40:
        return "Medium"
    else:
        return "Low"

song_metrics_scaled['Momentum_Level'] = song_metrics_scaled['momentum_score_final'].apply(momentum_level)

song_metrics_scaled[['momentum_score_final', 'Momentum_Level']].head()

   momentum_score_final Momentum_Level
0              0.360314            Low
1              0.208270            Low
2              0.351410            Low
3              0.351410            Low
4              0.314093            Low

In [81]:
#Count Songs in Each Category
momentum_counts = (
    song_metrics_scaled['Momentum_Level']
    .value_counts()
    .reset_index()
)

momentum_counts.columns = ['Momentum Level', 'Number of Songs']

momentum_counts

  Momentum Level  Number of Songs
0            Low              306
1         Medium              259
2           High                2

In [82]:
#Visualize the Categories
fig = px.pie(
    momentum_counts,
    names='Momentum Level',
    values='Number of Songs',
    title='Distribution of Songs by Momentum Level'
)

fig.show()

In [84]:
#Rank Recovery Speed Analysis
#Sort The Dataset
rank_df = df_clean.copy()

rank_df['date'] = pd.to_datetime(rank_df['date'], dayfirst=True)

rank_df = rank_df.sort_values(['song', 'date'])

In [85]:
#Previous Rank
rank_df['previous_position'] = rank_df.groupby('song')['position'].shift(1)

rank_df[['song', 'date', 'position', 'previous_position']].head()

                  song       date  position  previous_position
23425  1-800-hot-n-fun 2025-09-01        26                NaN
23477  1-800-hot-n-fun 2025-09-02        28               26.0
23527  1-800-hot-n-fun 2025-09-03        28               28.0
23581  1-800-hot-n-fun 2025-09-04        32               28.0
23644  1-800-hot-n-fun 2025-09-05        45               32.0

In [86]:
#Calculate Rank Recovery
rank_df['rank_recovery'] = rank_df['previous_position'] - rank_df['position']

rank_df[['song', 'position', 'previous_position', 'rank_recovery']].head()

                  song  position  previous_position  rank_recovery
23425  1-800-hot-n-fun        26                NaN            NaN
23477  1-800-hot-n-fun        28               26.0           -2.0
23527  1-800-hot-n-fun        28               28.0            0.0
23581  1-800-hot-n-fun        32               28.0           -4.0
23644  1-800-hot-n-fun        45               32.0          -13.0

In [87]:
#Average Recovery By Song
recovery_score = (
    rank_df.groupby('song')['rank_recovery']
    .mean()
    .reset_index()
)

recovery_score = recovery_score.sort_values(
    by='rank_recovery',
    ascending=False
)

recovery_score.head(15)

                                            song  rank_recovery
107           Darling, I (feat. Teezo Touchdown)      20.000000
261                               Lost and Found       9.500000
514                   i like the way you kiss me       8.000000
318                             OMG (FRNK Remix)       7.000000
10                       ??(??) (Untitled, 2014)       7.000000
325                                     PALISADE       7.000000
154                        Flights, Not Feelings       6.000000
473                          Underneath the Tree       5.666667
216  It's Beginning to Look a Lot like Christmas       5.666667
413             St. Chroma (feat. Daniel Caesar)       5.000000
352            Rockin' Around The Christmas Tree       4.666667
474                       V (Peace) (feat. AKMU)       4.333333
116        Don't Look Back In Anger - Remastered       4.000000
29                                All Or Nothing       4.000000
394                    Slime You Out (feat. SZA)       4.000000

In [88]:
#Visualization
fig = px.bar(
    recovery_score.head(15),
    x='rank_recovery',
    y='song',
    orientation='h',
    title='Top 15 Songs by Average Rank Recovery'
)

fig.show()

In [90]:
kpi = {}

# Total unique songs
kpi['Total Songs'] = song_metrics_scaled['song'].nunique()

# Total artists
kpi['Total Artists'] = song_metrics_scaled['artist'].nunique()

# Average Momentum Score
kpi['Average Momentum Score'] = round(
    song_metrics_scaled['momentum_score_final'].mean(), 3
)

# Maximum Momentum Score
kpi['Highest Momentum Score'] = round(
    song_metrics_scaled['momentum_score_final'].max(), 3
)

# Average Popularity
kpi['Average Popularity'] = round(
    song_metrics_scaled['avg_popularity'].mean(), 2
)

# Total Re-entries
kpi['Total Re-entries'] = int(
    song_metrics_scaled['reentry_count'].sum()
)

kpi

{'Total Songs': 526,
 'Total Artists': 194,
 'Average Momentum Score': np.float64(0.381),
 'Highest Momentum Score': 0.798,
 'Average Popularity': np.float64(0.68),
 'Total Re-entries': 35}

In [91]:
kpi_df = pd.DataFrame(
    kpi.items(),
    columns=['KPI', 'Value']
)

kpi_df

                      KPI    Value
0             Total Songs  526.000
1           Total Artists  194.000
2  Average Momentum Score    0.381
3  Highest Momentum Score    0.798
4      Average Popularity    0.680
5        Total Re-entries   35.000

In [92]:
#KPI Visualization
fig = px.bar(
    kpi_df,
    x='KPI',
    y='Value',
    text='Value',
    title='Project Key Performance Indicators'
)

fig.show()

In [94]:
#Correlation Analysis
correlation_df = song_metrics_scaled[[
    'avg_popularity',
    'total_days',
    'reentry_count',
    'momentum_score_final'
]]

correlation_df.corr()

,avg_popularity,total_days,reentry_count,momentum_score_final
avg_popularity,1.000000,0.264599,0.179399,0.869472
total_days,0.264599,1.000000,0.608624,0.685203
reentry_count,0.179399,0.608624,1.000000,0.546297
momentum_score_final,0.869472,0.685203,0.546297,1.000000

In [95]:
import plotly.express as px

corr = correlation_df.corr()

fig = px.imshow(
    corr,
    text_auto=True,
    color_continuous_scale='Viridis',
    title='Correlation Heatmap'
)

fig.show()

In [96]:
#Top 10 Momentum Songs
top_songs = (
    song_metrics_scaled
    .sort_values(
        'momentum_score_final',
        ascending=False
    )
    [['song', 'artist', 'momentum_score_final']]
    .drop_duplicates()
    .head(10)
)

top_songs

                     song        artist  momentum_score_final
130                 Ditto      NewJeans              0.797892
272            Like Crazy         Jimin              0.779459
109          Cruel Summer  Taylor Swift              0.727122
289         Love Me Again             V              0.723448
216              Hype Boy      NewJeans              0.722968
236      Interlude : Dive         Jimin              0.719453
143                   ETA      NewJeans              0.718095
333             New Jeans      NewJeans              0.709708
341                   OMG      NewJeans              0.700704
447  Standing Next to You     Jung Kook              0.699150

In [97]:
fig = px.bar(
    top_songs,
    x='momentum_score_final',
    y='song',
    color='artist',
    orientation='h',
    title='Top 10 Songs by Momentum Score'
)

fig.show()

In [99]:
song_metrics_scaled.to_csv("Final_SouthKorea_Analysis.csv", index=False)
print("CSV Saved Successfully!")

CSV Saved Successfully!

In [100]:
print(song_metrics_scaled.columns.tolist())

['song', 'artist', 'avg_popularity', 'total_days', 'reentry_count', 'momentum_score', 'momentum_score_final', 'album_type', 'is_explicit', 'Momentum_Level']

In [102]:
print(df.columns.tolist())

['date', 'position', 'song', 'artist', 'popularity', 'duration_ms', 'album_type', 'total_tracks', 'is_explicit', 'album_cover_url']

In [104]:
for col in song_metrics_scaled.columns:
    print(col)

song
artist
avg_popularity
total_days
reentry_count
momentum_score
momentum_score_final
album_type
is_explicit
Momentum_Level